/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as JokesRouteRouteImport } from './routes/jokes/route'
import { Route as JokeTableRouteRouteImport } from './routes/joke-table/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JokesIndexRouteImport } from './routes/jokes/index'
import { Route as JokeTableIndexRouteImport } from './routes/joke-table/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as JokesIdRouteImport } from './routes/jokes/$id'
import { Route as JokeTableUpdateRouteImport } from './routes/joke-table/update'
import { Route as JokeTableNewRouteImport } from './routes/joke-table/new'
import { Route as AuthResultRouteImport } from './routes/auth/result'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const JokesRouteRoute = JokesRouteRouteImport.update({
  id: '/jokes',
  path: '/jokes',
  getParentRoute: () => rootRouteImport,
} as any)
const JokeTableRouteRoute = JokeTableRouteRouteImport.update({
  id: '/joke-table',
  path: '/joke-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesIndexRoute = JokesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JokesRouteRoute,
} as any)
const JokeTableIndexRoute = JokeTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JokeTableRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const JokesIdRoute = JokesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JokesRouteRoute,
} as any)
const JokeTableUpdateRoute = JokeTableUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => JokeTableRouteRoute,
} as any)
const JokeTableNewRoute = JokeTableNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JokeTableRouteRoute,
} as any)
const AuthResultRoute = AuthResultRouteImport.update({
  id: '/auth/result',
  path: '/auth/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/joke-table': typeof JokeTableRouteRouteWithChildren
  '/jokes': typeof JokesRouteRouteWithChildren
  '/auth/result': typeof AuthResultRoute
  '/joke-table/new': typeof JokeTableNewRoute
  '/joke-table/update': typeof JokeTableUpdateRoute
  '/jokes/$id': typeof JokesIdRoute
  '/auth': typeof AuthIndexRoute
  '/joke-table/': typeof JokeTableIndexRoute
  '/jokes/': typeof JokesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/result': typeof AuthResultRoute
  '/joke-table/new': typeof JokeTableNewRoute
  '/joke-table/update': typeof JokeTableUpdateRoute
  '/jokes/$id': typeof JokesIdRoute
  '/auth': typeof AuthIndexRoute
  '/joke-table': typeof JokeTableIndexRoute
  '/jokes': typeof JokesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/joke-table': typeof JokeTableRouteRouteWithChildren
  '/jokes': typeof JokesRouteRouteWithChildren
  '/auth/result': typeof AuthResultRoute
  '/joke-table/new': typeof JokeTableNewRoute
  '/joke-table/update': typeof JokeTableUpdateRoute
  '/jokes/$id': typeof JokesIdRoute
  '/auth/': typeof AuthIndexRoute
  '/joke-table/': typeof JokeTableIndexRoute
  '/jokes/': typeof JokesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/joke-table'
    | '/jokes'
    | '/auth/result'
    | '/joke-table/new'
    | '/joke-table/update'
    | '/jokes/$id'
    | '/auth'
    | '/joke-table/'
    | '/jokes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/result'
    | '/joke-table/new'
    | '/joke-table/update'
    | '/jokes/$id'
    | '/auth'
    | '/joke-table'
    | '/jokes'
  id:
    | '__root__'
    | '/'
    | '/joke-table'
    | '/jokes'
    | '/auth/result'
    | '/joke-table/new'
    | '/joke-table/update'
    | '/jokes/$id'
    | '/auth/'
    | '/joke-table/'
    | '/jokes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JokeTableRouteRoute: typeof JokeTableRouteRouteWithChildren
  JokesRouteRoute: typeof JokesRouteRouteWithChildren
  AuthResultRoute: typeof AuthResultRoute
  AuthIndexRoute: typeof AuthIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jokes': {
      id: '/jokes'
      path: '/jokes'
      fullPath: '/jokes'
      preLoaderRoute: typeof JokesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joke-table': {
      id: '/joke-table'
      path: '/joke-table'
      fullPath: '/joke-table'
      preLoaderRoute: typeof JokeTableRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes/': {
      id: '/jokes/'
      path: '/'
      fullPath: '/jokes/'
      preLoaderRoute: typeof JokesIndexRouteImport
      parentRoute: typeof JokesRouteRoute
    }
    '/joke-table/': {
      id: '/joke-table/'
      path: '/'
      fullPath: '/joke-table/'
      preLoaderRoute: typeof JokeTableIndexRouteImport
      parentRoute: typeof JokeTableRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jokes/$id': {
      id: '/jokes/$id'
      path: '/$id'
      fullPath: '/jokes/$id'
      preLoaderRoute: typeof JokesIdRouteImport
      parentRoute: typeof JokesRouteRoute
    }
    '/joke-table/update': {
      id: '/joke-table/update'
      path: '/update'
      fullPath: '/joke-table/update'
      preLoaderRoute: typeof JokeTableUpdateRouteImport
      parentRoute: typeof JokeTableRouteRoute
    }
    '/joke-table/new': {
      id: '/joke-table/new'
      path: '/new'
      fullPath: '/joke-table/new'
      preLoaderRoute: typeof JokeTableNewRouteImport
      parentRoute: typeof JokeTableRouteRoute
    }
    '/auth/result': {
      id: '/auth/result'
      path: '/auth/result'
      fullPath: '/auth/result'
      preLoaderRoute: typeof AuthResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface JokeTableRouteRouteChildren {
  JokeTableNewRoute: typeof JokeTableNewRoute
  JokeTableUpdateRoute: typeof JokeTableUpdateRoute
  JokeTableIndexRoute: typeof JokeTableIndexRoute
}

const JokeTableRouteRouteChildren: JokeTableRouteRouteChildren = {
  JokeTableNewRoute: JokeTableNewRoute,
  JokeTableUpdateRoute: JokeTableUpdateRoute,
  JokeTableIndexRoute: JokeTableIndexRoute,
}

const JokeTableRouteRouteWithChildren = JokeTableRouteRoute._addFileChildren(
  JokeTableRouteRouteChildren,
)

interface JokesRouteRouteChildren {
  JokesIdRoute: typeof JokesIdRoute
  JokesIndexRoute: typeof JokesIndexRoute
}

const JokesRouteRouteChildren: JokesRouteRouteChildren = {
  JokesIdRoute: JokesIdRoute,
  JokesIndexRoute: JokesIndexRoute,
}

const JokesRouteRouteWithChildren = JokesRouteRoute._addFileChildren(
  JokesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JokeTableRouteRoute: JokeTableRouteRouteWithChildren,
  JokesRouteRoute: JokesRouteRouteWithChildren,
  AuthResultRoute: AuthResultRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
